import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { readFileSync } from "fs";
import { componentTagger } from "lovable-tagger";
import prerender from "@prerenderer/rollup-plugin";
import PuppeteerRenderer from "@prerenderer/renderer-puppeteer";

// Generated by scripts/generate-routes.ts (prebuild hook).
const prerenderRoutes: string[] = JSON.parse(
  readFileSync(path.resolve(__dirname, "prerender-routes.json"), "utf-8"),
);

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  base: "/",
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [
    react(),
    mode === 'development' && componentTagger(),
    // Static prerender for production build only — generates full HTML
    // so crawlers and social previews see real content, while the SPA
    // hydrates and behaves normally in the browser.
    mode === 'production' && prerender({
      routes: prerenderRoutes,
      renderer: new PuppeteerRenderer({
        renderAfterDocumentEvent: 'render-event',
        headless: true,
        maxConcurrentRoutes: 2,
      }),
    }),
  ].filter(Boolean),

  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
}));
