// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwwpidktaanowpaihgzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3d3BpZGt0YWFub3dwYWloZ3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDIyOTcsImV4cCI6MjA2MDY3ODI5N30.qvUw8w0DAQ8nnqyevugAp0V22fAUAVx9-TSD_gIqRQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);